In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [33]:
y2015 = pd.read_csv('C:\\Users\\cocob\\Downloads\\LoanStats3d.csv', skipinitialspace=True, header=1)

c:\users\cocob\appdata\local\continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [34]:
y2015.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68009401,72868139.0,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,C5,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,68354783,73244544.0,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,A4,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,68466916,73356753.0,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,A4,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,68466961,73356799.0,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,A2,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,68495092,73384866.0,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,E3,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0

In [35]:
y2015.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
       'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens',
       'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit'],
      dtype='object', length=111)

In [36]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

In [37]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120596
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
33
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3

In [38]:
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [39]:
y2015 = y2015[:-2]

In [40]:
y2015['verification_status_joint']

0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10        Not Verified
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN
22                 NaN
23                 NaN
24                 NaN
25                 NaN
26                 NaN
27                 NaN
28                 NaN
29                 NaN
              ...
421067             NaN
421068             NaN
421069             NaN
421070             NaN
421071             NaN
421072             NaN
421073             NaN
421074             NaN
421075             NaN
421076             NaN
421077             NaN
421078             NaN
421079             NaN
421080             NaN
421081             NaN
421082             NaN
421083             NaN
421084             NaN
421085             NaN
421086             NaN
421087             NaN
421088             NaN
421089             NaN
421090             NaN
421091             NaN
421092             NaN
421093             NaN
421094             NaN
421095             NaN
421096             NaN
Name: verification_status_joint, Length: 421097, dtype: object

In [41]:
pd.get_dummies(y2015['grade'])

        A  B  C  D  E  F  G
0       0  0  1  0  0  0  0
1       1  0  0  0  0  0  0
2       1  0  0  0  0  0  0
3       1  0  0  0  0  0  0
4       0  0  0  0  1  0  0
5       0  1  0  0  0  0  0
6       0  0  1  0  0  0  0
7       0  0  1  0  0  0  0
8       0  0  1  0  0  0  0
9       0  0  0  0  0  1  0
10      0  1  0  0  0  0  0
11      0  0  1  0  0  0  0
12      0  0  1  0  0  0  0
13      0  0  1  0  0  0  0
14      0  0  1  0  0  0  0
15      1  0  0  0  0  0  0
16      0  0  1  0  0  0  0
17      0  0  1  0  0  0  0
18      0  0  0  0  1  0  0
19      0  1  0  0  0  0  0
20      0  1  0  0  0  0  0
21      0  1  0  0  0  0  0
22      0  0  1  0  0  0  0
23      0  0  1  0  0  0  0
24      1  0  0  0  0  0  0
25      0  0  1  0  0  0  0
26      1  0  0  0  0  0  0
27      1  0  0  0  0  0  0
28      1  0  0  0  0  0  0
29      0  0  1  0  0  0  0
...    .. .. .. .. .. .. ..
421067  1  0  0  0  0  0  0
421068  0  0  0  1  0  0  0
421069  1  0  0  0  0  0  0
421070  0  0  0  1  0  0  0
421071  0  0  0  1  0  0  0
421072  0  0  0  1  0  0  0
421073  0  1  0  0  0  0  0
421074  0  0  0  1  0  0  0
421075  0  1  0  0  0  0  0
421076  0  0  0  1  0  0  0
421077  1  0  0  0  0  0  0
421078  1  0  0  0  0  0  0
421079  0  1  0  0  0  0  0
421080  1  0  0  0  0  0  0
421081  0  0  1  0  0  0  0
421082  0  0  0  1  0  0  0
421083  1  0  0  0  0  0  0
421084  0  0  1  0  0  0  0
421085  0  1  0  0  0  0  0
421086  0  1  0  0  0  0  0
421087  0  0  0  0  1  0  0
421088  0  0  0  1  0  0  0
421089  0  1  0  0  0  0  0
421090  0  1  0  0  0  0  0
421091  0  1  0  0  0  0  0
421092  0  0  0  1  0  0  0
421093  0  0  0  0  1  0  0
421094  0  1  0  0  0  0  0
421095  0  0  0  0  0  0  0
421096  0  0  0  0  0  0  0

[421097 rows x 7 columns]

In [56]:
#rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = np.array(X.dropna(axis=1))
Y = pd.get_dummies(Y)
Y.current = np.array(Y['Current'])
#cross_val_score(rfc, X, Y, cv=10)
print(Y.current)

[1 1 0 ... 1 0 0]

c:\users\cocob\appdata\local\continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  import sys

In [59]:
##PCA

from sklearn.decomposition import PCA

In [60]:
pca= PCA(n_components=10)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [61]:
print(pca.explained_variance_ratio_)

[0.10590681 0.07940555 0.06793654 0.06355587 0.06037494 0.05156646
 0.04040358 0.03838491 0.03258114 0.02998921]

In [66]:
Xp= pca.fit(X)
Xp2 = pca.singular_values_
print(Xp2)
np.shape(Xp2)

[558.99870388 484.03224636 447.7138964  433.03869411 422.06291972
 390.06099251 345.26996191 336.53413498 310.05007787 297.46174983]

(10,)

In [47]:
print(np.shape(X))

(421097, 143)

In [57]:
rfc = ensemble.RandomForestClassifier()

In [58]:
cross_val_score(rfc, X, Y.current, cv=10)

array([0.97371233, 0.93051697, 0.93289164, 0.94067917, 0.85872379,
       0.92740269, 0.81303284, 0.94533235, 0.75230948, 0.62649315])

In [75]:
#rfc = ensemble.RandomForestClassifier()
X = y2015[:, 0:9]
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = np.array(X.dropna(axis=1))
Y = pd.get_dummies(Y)
Y.current = np.array(Y['Current'])
#cross_val_score(rfc, X, Y, cv=10)

TypeError: unhashable type: 'slice'

In [71]:
rfc = ensemble.RandomForestClassifier()

In [76]:
cross_val_score(rfc, Xp, Y, cv=10)

TypeError: Singleton array array(PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False), dtype=object) cannot be considered a valid collection.